http:
  middlewares:
    jwt-auth:
      plugin:
        jwt:
          jwksUrl: '{{ env "ZITADEL_JWKS_URL" }}'
          headerMap:
            sub: X-User-ID
            email: X-User-Email
            name: X-User-Name
