keycloak_admin_realm: master
keycloak_scheme: http
keycloak_http_port: 8080
keycloak_service_name: keycloak
keycloak_full_admin_realm_role: admin
keycloak_app_realm: home-stack
keycloak_app_realm_display_name: home-stack
keycloak_default_client_scopes:
  - basic
  - profile
  - email
  - roles
keycloak_optional_client_scopes: []
keycloak_client_registration_policy_provider_type: org.keycloak.services.clientregistration.policy.ClientRegistrationPolicy
keycloak_dcr_policy_components:
  - name: Trusted Hosts
    provider_id: trusted-hosts
    sub_type: anonymous
    config:
      trusted-hosts:
        - localhost
        - claude.ai
        - claude.com
      host-sending-registration-request-must-match:
        - "false"
      client-uris-must-match:
        - "true"
  - name: Allowed Registration Web Origins
    provider_id: registration-web-origins
    sub_type: anonymous
    config:
      web-origins:
        - https://claude.ai
        - https://claude.com
