domain: ENC[AES256_GCM,data:6CC/fevp7+0fxeJUlvY=,iv:GlASwWWn6MIBkiL1LPpNAONGGrR2Va3xXh1T03rJprw=,tag:Z44YAGkxQIbb2VK+gkQK1g==,type:str]
acme_email: ENC[AES256_GCM,data:D9dTvGBLR7EjZs5E4M0/QYFj27k=,iv:GcLgpMJCnYVYCK/DfvTUfEs13hVv1ihgGYTj9Bph9AU=,tag:R6ryLjlKlv984vC0wYOUlg==,type:str]
#ENC[AES256_GCM,data:n13jkMwStNI7sRnCI1+MDWG8S1Kl//i43A001OHhlHsjLhKpN1gMrqYRGDWd0Z23gQ==,iv:MwiG2cioK1BRoq45Ede4RNAAkLyW7x4p1xOmhPz42TQ=,tag:I/t1EMWNSRFFuTp/xBU4Rw==,type:comment]
#ENC[AES256_GCM,data:VORNwY/idqDLoj/goyL1F5RhngItNi62wF03g/edOGTGhVn9yNc/1OygOg==,iv:8d7tsfU8ZMz6nS2kVspML4V7I/lOQ7DIzuQDf9AZNuQ=,tag:4Jq0LK20BNcxNaFh1VoqPw==,type:comment]
#ENC[AES256_GCM,data:lJF39IOelVX4rsvmiqmGnjHapuFz7PsF+bqpC9ccYypAdE2zKUQMeoAPEhZYRN2+bv2Alu2kDUhS49xESRBVJTOKyw==,iv:LTm7VjM0qAASyXfViS3nCtffrEILV3+4Ms/Te6gPJDc=,tag:Mfho6DBs24gf+t6IRbAc2g==,type:comment]
#ENC[AES256_GCM,data:lek7nWf+9z0F2gbMov1UssP7MMG1aqt/xsdnY6eTVouhgjxTzzTAaSNnGZcS5XYIjkiMjwHpJZPDzJkr,iv:2d2l5hh3GEBec7iTh/b9AJCr1uEwzJkwwUF35VySuOg=,tag:hEPyuTxSDDjmvUR3kpL9oA==,type:comment]
#ENC[AES256_GCM,data:7OMBcvX2TjzZ3mN7uMsQaQwumHOjRoSILVILSmD3nYYYIr2FcTzYNQ==,iv:6lKSXf/PyGdpup9kE+khXLNEJdFzQnwKaRxbMvQ9YCk=,tag:O1+jmKUqBLIHd6WuN40I4Q==,type:comment]
pg_admin_password: ENC[AES256_GCM,data:xdKoJU0oxPi+VTj5J5s0qdC6HKT/NjWi8id71szM5Xk=,iv:65bzDGrWQ9HgNVzdcP3BD4yRR0UzlO3RmKhF8Eqs5U4=,tag:uDvD1/oBncIwX4O1I1ti0w==,type:str]
#ENC[AES256_GCM,data:n13jkMwStNI7sRnCI1+MDWG8S1Kl//i43A001OHhlHsjLhKpN1gMrqYRGDWd0Z23gQ==,iv:MwiG2cioK1BRoq45Ede4RNAAkLyW7x4p1xOmhPz42TQ=,tag:I/t1EMWNSRFFuTp/xBU4Rw==,type:comment]
#ENC[AES256_GCM,data:kswfBHio1qTF5cz3beX+TsbQoqCifs0gMfJoUmoaTp/7AhMyIAT/puLHJJpjsUE2aGmG3xvkbaB59EScDiM623pnJLWRrisjpDKe,iv:Yg9HylfH7Xvz8qo+wQfX7+sqbv8kXtO+xaQjLUhga7U=,tag:b7h3NMRVGAfsFyxpHfAfqw==,type:comment]
#ENC[AES256_GCM,data:7OMBcvX2TjzZ3mN7uMsQaQwumHOjRoSILVILSmD3nYYYIr2FcTzYNQ==,iv:6lKSXf/PyGdpup9kE+khXLNEJdFzQnwKaRxbMvQ9YCk=,tag:O1+jmKUqBLIHd6WuN40I4Q==,type:comment]
keycloak_admin_password: ENC[AES256_GCM,data:BleszZgu76QInUzd2cBToU9lmCVzx9CK04V6KZW3sw8=,iv:uM7XQpV+pwPYMNVYCk1eOSCGVYNJnFkDip93BFCNWXo=,tag:F6xtJFSFEWYfytPR5Xqcrg==,type:str]
keycloak_admin_allowed_ips: ENC[AES256_GCM,data:5HkFESeQ7dJu4w2oNuCTpw==,iv:ManEp2KaiNIiWw0BSYHyPDdcYbz2HXJqLf7/gd6topc=,tag:k28uP1OZn1Yydj6crjn8cg==,type:str]
google_identity_provider:
    enabled: ENC[AES256_GCM,data:XGyYaQ==,iv:zXCE0cRwL/B+QHtaGJsjeJVt0C+AmTobbkiHT6376KE=,tag:gRy4rft4MgA1UQ3Bv+GnaA==,type:bool]
    client_id: ENC[AES256_GCM,data:rul+v1vrRi3rMUklfXhBd64/vMNVKNFnRP8+E+uG+67inPuGMIw4EJ3v55Kj1PGlCUZH3bIu+dqW6RY6yNp7CCXFOp90Q2R4,iv:1xdueAoFGXXXrwP6RSBQhh6oQ0HTmr29ly5MTCN4m9w=,tag:2/7d/FoC/Sj2xnWI6OGN2w==,type:str]
    client_secret: ENC[AES256_GCM,data:tQvJRUkao9rxEyqfoG9xghqMIWFCO/UNerjO+AUYU6PTsUQ=,iv:I86lDgwf31LVVKHSp7yLHEqTsFg4R7/Ykrt0cmtXtcM=,tag:c3yaZKfsX+TPqr8YzaucOQ==,type:str]
    hosted_domain: ""
watchtower_http_api_token: ENC[AES256_GCM,data:qxK6ukyWHhKVNVcWlRONjaBmhHytQuCHB0+weHcTiJo=,iv:1wbUZFNVmMTSVdS+wmW9XCgNNzWMcvEkDM56/0sd+8E=,tag:LrB3Py388NZjx/iiLB2gSQ==,type:str]
sops:
    age:
        - recipient: age10nhj5vu84j0ezxvl0q69wykytvt5m8q9d2y04kxs2e46daf70d0qul3pyl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVUVuQWxVdS91bjAyTmJ5
            RGVVcWhkVkVHaDdKVkhsVk02a25BK3FlTDJFCjFLeWNUaDdXSzZLUndDN2dScTZW
            K2xOajd5WExUS2p1OFBiVXpJSElIOUUKLS0tIHEwZWVPVEIrL081K0QwSjJhTVBL
            T1NKdlN6WFNZSU5RQ3FaQ3NGTWhpaTgK/tedi9qGuZi8rHuSvQW4BOpuB3Q04N0W
            2WL/CaRPWFMHSOY8aWPch/NJ5adsNLjHU0wFCLVxKvHjOg/6ipQX0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T16:35:44Z"
    mac: ENC[AES256_GCM,data:fVEBN8zdbInywzD2kKoluzWuchZSIVI6iADGA4wsny1obosoOFOZ+PJ9YOgjPrrQuEJid1lQkMBZg42pyz8PtTCvUhNWvLogXnvs0CrpdE7zE9rP3FtK8BrEsCI8T8tHVRXI7dOfA45NQMoNY3uCLSm9xVQlDJLYYHkUleqYB30=,iv:8jbRjlOgzSvjRYK4UtION7wprQMzqc72gUZTTHIQj10=,tag:jdd24PYasm4WrY9qqIDRGA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
